apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic
  labels:
    app: springpetclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
        - name: springpetclinic
          image: sanabargaoui/springpetclinic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
