apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
spec:
  type: NodePort
  selector:
    app: springpetclinic
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 30080

